Count,Message,Traceback,Nodes
22,404 Client Error: Not Found for url: https://messaging-backend-service-275962547711.us-central1.run.app/api/users/login,"  File ""/Users/emrec/Desktop/mobileapp/.venv/lib/python3.13/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File ""/Users/emrec/Desktop/mobileapp/.venv/lib/python3.13/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/Users/emrec/Desktop/mobileapp/.venv/lib/python3.13/site-packages/locust/user/task.py"", line 487, in execute_task
    task(self.user).run()
    ~~~~~~~~~~~~~~~~~~~^^
  File ""/Users/emrec/Desktop/mobileapp/.venv/lib/python3.13/site-packages/locust/user/task.py"", line 325, in run
    self.on_start()
    ~~~~~~~~~~~~~^^
  File ""/Users/emrec/Desktop/mobileapp/locustfile.py"", line 27, in on_start
    r.raise_for_status()
    ~~~~~~~~~~~~~~~~~~^^
  File ""/Users/emrec/Desktop/mobileapp/.venv/lib/python3.13/site-packages/requests/models.py"", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
",local
1,403 Client Error: Forbidden for url: https://messaging-backend-service-275962547711.us-central1.run.app/api/users/register,"  File ""/Users/emrec/Desktop/mobileapp/.venv/lib/python3.13/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File ""/Users/emrec/Desktop/mobileapp/.venv/lib/python3.13/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/Users/emrec/Desktop/mobileapp/.venv/lib/python3.13/site-packages/locust/user/task.py"", line 487, in execute_task
    task(self.user).run()
    ~~~~~~~~~~~~~~~~~~~^^
  File ""/Users/emrec/Desktop/mobileapp/.venv/lib/python3.13/site-packages/locust/user/task.py"", line 325, in run
    self.on_start()
    ~~~~~~~~~~~~~^^
  File ""/Users/emrec/Desktop/mobileapp/locustfile.py"", line 20, in on_start
    r.raise_for_status()
    ~~~~~~~~~~~~~~~~~~^^
  File ""/Users/emrec/Desktop/mobileapp/.venv/lib/python3.13/site-packages/requests/models.py"", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
",local
